<x-partials.pages.home.slider-area />
<x-partials.pages.home.about-area />
<x-partials.pages.home.service-area />
<x-partials.pages.home.our-skill-area />
<x-partials.pages.home.faq-area />
<x-partials.pages.home.welcome-area />
<x-partials.pages.home.team-area />
<x-partials.pages.home.working-with-us-area />
<x-partials.pages.home.portfolio-area />
<x-partials.pages.home.pricing-area />
<x-partials.pages.home.customer-comments-area />
<x-partials.pages.home.last-news-area />
<x-partials.pages.home.message-area />
